# service
server:
  servlet:
    context-path: /fd_iterm
  port: 80

spring:
  # redis
  redis:
    host: 39.106.81.183
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

  # mybatis
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze1tb28p0w98f7dumo.mysql.rds.aliyuncs.com:3306/fd_iterm
    username: suiliangliang
    password: suiliangliang123
    type: com.alibaba.druid.pool.DruidDataSource

############################# druid连接池 ##################################
#初始化连接大小
spring.druid.initialSize: 5
#最小连接池数量
spring.druid.minIdle: 5
#最大连接池数量
spring.druid.maxActive: 20
#获取连接时最大等待时间，单位毫秒
spring.druid.maxWait: 60000
#配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.druid.timeBetweenEvictionRunsMillis: 60000
#配置一个连接在池中最小生存的时间，单位是毫秒
spring.druid.minEvictableIdleTimeMillis: 300000
#测试连接
spring.druid.validationQuery: SELECT 1 FROM DUAL
#申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
spring.druid.testWhileIdle: true
#获取连接时执行检测，建议关闭，影响性能
spring.druid.testOnBorrow: false
#归还连接时执行检测，建议关闭，影响性能
spring.druid.testOnReturn: false
#是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
spring.druid.poolPreparedStatements: false
#开启poolPreparedStatements后生效
spring.druid.maxPoolPreparedStatementPerConnectionSize: 20
#配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
spring.druid.filters: stat,wall,log4j
# 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
spring.druid.connectionProperties:

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.fd.fd_iterm.domain
